name: CI - Build Versioned Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: backend-api
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image with commit SHA
        run: |
          docker build \
            --build-arg APP_VERSION=${IMAGE_TAG} \
            --build-arg GIT_COMMIT=${IMAGE_TAG} \
            -t $IMAGE_NAME:$IMAGE_TAG \
            -f docker/Dockerfile \
            .


